apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: h8j7y0tb9-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/h8j7y0tb9-java-springboot-gitops